### PR TITLE
[WIP] Add support for odroid-c1

### PR DESCRIPTION
**Pull request by zimme**

### CODE REVIEW

**Comment by luxas** [comment]
I'm a bit curious if Kubernetes runs on odroid. Does it with this merged in?
I was really thinking about adding this kind of support, but since I don't have any of those boards, I can't test it. Really glad you sent this PR, so we could get `odroid` with us.
Do you have odroid-xu3 or odroid-xu4? I may add support for those boards at the same time

How about the kernel? Is it new enough to support e.g. `overlay` storage driver?

**Comment by zimme** [comment]
It might be premature to merge this actually, as I haven't gotten k8s working yet. Started with this yesterday. fiddled a bit today, and the kernel for c1/c1+ is at 3.10.80, I know there's 4.2 or something for xu4. I don't have any other odroid boards.

So it doesn't seem to support overlay storage, I've gotten a bit further by removing the `docker-overlay.conf` file.

**Comment by luxas** [comment]
Maybe we should delay this one then after `v0.6.3` which I'm about to release now. 
WDYT?

**Comment by zimme** [comment]
I don't feel it's necessary to merge this until we have something that works as intended. But we can keep it here to track progress to see if we ever can get to a point where we have everything working as intended.

I've seen a thread about someone working on rebasing the odroid-c1 kernel onto 4.x.

**Comment by luxas** [comment]
Sounds good. Thanks for your interest and will to improve :)

**Comment by zimme** [comment]
I've gotten docker and system-docker running now, just had add this to `boards/odroid-c1.sh`:
```sh
sed -e "s@-s overlay@@" -i $ROOT/usr/lib/systemd/system/system-docker.service
```
Which I think parallella needs to as it does not have overlay support also.

But I'm getting `resource` errors, I think it's related to flannel, investigating.

**Comment by luxas** [comment]
Seems like we have come to the same conclusion about old kernels: 6cb7e8a613ac21be5758dc742fdeb3d932eb7290
Added it when I began (partially)supporting the Parallella.

I hadn't remembered to add it for `system-docker` though, feel free to include that in your PR.
Where are you getting `resource` errors? In `docker.service`, or something else?

**Comment by zimme** [comment]
Getting it in `docker.service` when trying to enable-worker, same fir the rpi-2 actually...

**Comment by zimme** [comment]
```sh
Jan 12 15:57:24 rpi systemd[1]: docker.service: Failed to load environment files: No such file or directory
Jan 12 15:57:24 rpi systemd[1]: docker.service: Failed to run 'start-pre' task: No such file or directory
Jan 12 15:57:24 rpi systemd[1]: Failed to start Docker Application Container Engine.
Jan 12 15:57:24 rpi systemd[1]: docker.service: Unit entered failed state.
Jan 12 15:57:24 rpi systemd[1]: docker.service: Failed with result 'resources'.
```

**Comment by luxas** [comment]
OK, it's `flannel` then. What does `systemctl status flannel` and `ls /var/lib/kubernetes/flannel` output?

**Comment by zimme** [comment]
flannel is running but i get this
```sh
Jan 12 16:03:03 rpi docker[294]: E0112 15:03:03.749674 00001 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
```
`ls /var/kubernetes/flannel` gives me nothing

**Comment by luxas** [comment]
Seems something is wrong either with your master `etcd` instance or with `/etc/kubernetes/k8s.conf`.
On your master, is `etcd` working and is `K8S_MASTER_IP` really pointing to your master?

**Comment by zimme** [comment]
`k8s.conf` in master ( archlinux on rpi)
```
K8S_MASTER_IP=127.0.0.1
FLANNEL_SUBNET=10.1.0.0/16
DNS_DOMAIN=cluster.local
DNS_IP=10.0.0.10
```

`k8s.conf` in worker ( archlinux on rpi-2)
```
K8S_MASTER_IP=192.168.1.20
FLANNEL_SUBNET=10.1.0.0/16
DNS_DOMAIN=cluster.local
DNS_IP=10.0.0.10
```

**Comment by luxas** [comment]
And how about `etcd`?

**Comment by zimme** [comment]
```
Jan 11 01:00:36 rpi docker[221]: 2016-01-11 00:00:36.374620 I | etcdserver: loaded cluster information from store: <nil>
Jan 11 01:00:41 rpi sh[222]: Error:  client: etcd cluster is unavailable or misconfigured
Jan 11 01:00:41 rpi sh[222]: error #0: dial tcp 127.0.0.1:2379: connection refused
Jan 11 01:00:41 rpi sh[222]: error #1: client: endpoint http://127.0.0.1:4001 exceeded header timeout
Jan 11 01:00:58 rpi systemd[1]: etcd.service: Control process exited, code=exited status=4
Jan 11 01:01:00 rpi docker[264]: k8s-etcd
Jan 11 01:01:00 rpi systemd[1]: etcd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 11 01:01:00 rpi systemd[1]: Failed to start Etcd Master Data Store for Kubernetes Apiserver.
Jan 11 01:01:00 rpi systemd[1]: etcd.service: Unit entered failed state.
Jan 11 01:01:00 rpi systemd[1]: etcd.service: Failed with result 'exit-code'.
```

**Comment by luxas** [comment]
OK, that's the problem. Has it worked before or didn't it ever start?
Sometimes, `etcd` just fails on start when it tries to load data from `/var/lib/kubernetes/etcd`
That's an `etcd` issue though. Added a small note about it in the readme.
I always `delete-data` when this happens, but I don't know if you are storing some important data there.

But didn't the `enable-worker` command fail because of no `apiserver`?

**Comment by zimme** [comment]
Haven't played around to much, I'll try and disable master and worker and delete data to get back to a "clean" state and then I'll try again. but that won't be until tonight. =)

**Comment by luxas** [comment]
Ping @zimme 
Have you got it working?

Hypriot also have a C1 version, so I may add that one easily too, but the kernel version is still `3.10` something...

**Comment by zimme** [comment]
Hey, so I'm out traveling for 3 month so it's ön hold for now. I didn't have enough time to get into trying to get 4.x to work on the c1 before i left either. Maybe the hypriot option is better for now.

**Comment by luxas** [comment]
It's really ok, no need to rush on this. When `hypriot` gets a newer kernel running on their `odroid c1` and maybe `c2`, then we could look into this again.

After all, the `sdcard` creation process became less important when I made the `.deb` package in `v0.6.2`

Happy travelling!

**Comment by zimme** [comment]
I don't see myself having a lot of time doing this work in the near future, just thought you should know.

But in light of the work with odroid-c2 being done, maybe that will work for odroid-c1(+) boards too?

**Comment by zimme** [comment]
I'm closing this PR and removing my branch and fork as this project isn't active any more and I haven't had time to work on this.

**Pull request closed without merging**
