### PR TITLE
Make path to kubectl explicit

### PR DESCRIPTION
**Pull request by DorianGray**
This solves some issues where $PATH might not include the kubernetes binaries directory. Currently, master on hypriotos has this issue.

### CODE REVIEW

**Comment by luxas** [comment]
See issue: #65

**Comment by DorianGray** [comment]
Yeah, exact same issue. Do you not like the approach to solving it here? What do you think should be done differently?

**Comment by luxas** [comment]
Could you 
```
BINARIES_DIR=$KUBERNETES_DIR/binaries
KUBECTL="$BINARIES_DIR/kubectl"
```
and use `${KUBECTL}` everywhere instead?

Thanks for the patch. It'll improve UX for `sudo`ers, and that's good.

**Comment by DorianGray** [comment]
@luxas better?

**Comment by luxas** [comment]
Yes, LGTM

**Pull request merged**
