### PR TITLE
WIP: Release v0.8.0

### PR DESCRIPTION
**Pull request by luxas**
Work in progress!
@larmog Here you may comment. It's still possible to send PRs to dev as normal
This PR will update as I work more on the release

### CODE REVIEW

**Comment by larmog** [comment]
The problem with docker-multinode is that the volume "data" that get mounted in /srv/kubernetes is of type "emptyDir". When the apiserver POD dies (and it will on arm) and restarts it will generate new certificates. This makes all services that talks to apiserver fail with "unknown certificate auth".

I've made a small script that copies /etc/kubernetes from hyperkube and modifies the volume to be "hostPath". It the mounts the new /etc/kubernetes files to the kubelet docker container, and it seems to work.

I've also modified common.sh so that it keeps etcd data between restarts.

**Comment by luxas** [comment]
> I've also modified common.sh so that it keeps etcd data between restarts.

Good catch! Feel free to send a PR against kube-deploy with this, otherwise I'll do it

**Comment by larmog** [comment]
Ok, here it is: https://github.com/kubernetes/kube-deploy/pull/175

**Comment by luxas** [comment]
Yeah, finally!

Let's release v0.8.0!

**Pull request merged**
