### PR TITLE
Updated from kubernetes/contrib/service-loadbalancer.

### PR DESCRIPTION
**Pull request by larmog**
This service-loadbalancer works for me.
This is the diff from the original template.cfg and my changes:
```
87c87
<     bind :443 ssl {{ .sslCert }} ciphers no-sslv3
---
>     bind :443 ssl {{ .sslCert }} 
169c169,170
< 
---
>     # TODO: Make the path used to access a service customizable.
>     reqrep ^([^\ :]*)\ /{{$svc.Name}}[/]?(.*) \1\ /\2
```
I removed the ciphers no-sslv3 entry because it gave me an error.
Hope this helps!

### CODE REVIEW

**Comment by luxas** [comment]
So just to clarify, you have copied the latest files from `contrib/service-loadbalancer`, removed `no-sslv3` and added `/{{svc.Name}}` (e.g. `/my-nginx`)
It looks good to me, and I'll test it soon.

**Comment by luxas** [comment]
And a side note, when I first tried `loadbalancer` out, `serviceAccounts` weren't created. 
I fixed `serviceAccounts` in `v0.6.0`, so it shouldn't be a problem now.

**Comment by larmog** [comment]
Hi,
Yes and used the latest binary from contrib/service-loadbalancer. Apparently they fixed som ssl-stuff. I didn’t do much.
/Regards

**Comment by luxas** [comment]
LGTM, thanks!

**Pull request merged**
